title: Ben Foley
author: ben foley
email: benjafo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 ben foley
theme: minima

# social links
github_username:  benjafo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
